### ISSUE TITLE
Unit testing framework

### ISSUE THREAD

**Issue by floriandejonckheere** [OpenWebslides/OpenWebslides#17]

**Comment by RubenVerborgh** [comment]
I'm a huge fan of Mocha because of its flexibility (I have the same tests running on Node, browser, and other platforms), and you can use it with assertion frameworks of your choice (I like Chai). There's also [https://github.com/avajs/ava](AVA) though, but I don't have any experience with it.

**Comment by floriandejonckheere** [comment]
I think the most used packages are Mocha+Chai, so I'm going to use those.
