### ISSUE TITLE
FEED: Decks are not shown when redirected on sign in

### ISSUE THREAD

**Issue by reinvanimschoot** [OpenWebslides/OpenWebslides#226]

**Comment by reinvanimschoot** [comment]
Apparently it solved itself while rebasing, fixing other stuff

**Comment by reinvanimschoot** [comment]
<img width="1426" alt="screen shot 2017-09-05 at 15 07 26" src="https://user-images.githubusercontent.com/19598519/30062583-fb71efc2-924b-11e7-8819-37ca626d734b.png">

I am logged in but I cannot see any decks until I refresh once more

**Comment by ldorigo** [comment]
Should be good now!
