### ISSUE TITLE
Send Veerle an email notification when annotation is added

### ISSUE THREAD

**Issue by reinvanimschoot** [OpenWebslides/OpenWebslides#409]
Since the exams are on their way, Veerle is expecting more questions to be added as annotations. Unfortunately, it's not easy for her to see what annotations have been added and where. So it would be great if she received a mail when an annotation is created.

Depending on the possibilities, the following info would be nice to provide:

- Annotation text
- Link to deck and slide
- Author

If it all possible, it would also be superb if that author ( the student) would receive a mail when someone responded to their annotation. 

But that's a nice to have.

**Comment by floriandejonckheere** [comment]
If I have analyzed it correctly, when a Conversation gets posted, the deck author should be notified. When a Comment gets posted, the parent Conversation's author gets notified. Should the deck author also get notified in the latter case?
