### ISSUE TITLE
Cross-platform compatibility

### ISSUE THREAD

**Issue by floriandejonckheere** [OpenWebslides/OpenWebslides#94]
- [ ] Binary packages of `nokogiri` for Windows have a Ruby dependency < 2.4, >= 2.1.0

**Comment by Dromin** [comment]
Todo: fix the problem where `bundle install` will install a broken version of bcrypt, which then has to be manually uninstalled. See [here](https://github.com/codahale/bcrypt-ruby/issues/149).

**Comment by floriandejonckheere** [comment]
Package rebuilt, dependency changed to `< 2.5, >= 2.2`
