### ISSUE TITLE
Frontend cannot be run separately from backend because index file is provided by Rails

### ISSUE THREAD

**Issue by Dromin** [OpenWebslides/OpenWebslides#97]
Currently, the frontend cannot be run separately from the backend (by executing `webpack-dev-server --config config/webpack.config.js`) because the index.html file is generated in the backend by Ruby on Rails. This causes the webpack-dev-server to display a directory listing, instead of the React app. 

I think it might be better to keep the backend and frontend completely separate from each other, but there might be something that I've missed. Is this an issue that needs fixing?

**Comment by floriandejonckheere** [comment]
For the development phase we integrated webpack into the Rails pipeline, but ultimately the HTML and JS files should be served from a CDN, meaning that the frontend is fully uncoupled from the backend.

It's on the operations TODO list, but there wasn't an issue for it.

**Comment by floriandejonckheere** [comment]
Rails 5.1 provides support for Yarn and Webpack in different environments. Perhaps we could use this to our advantage.

**Comment by floriandejonckheere** [comment]
Fixed in `uncouple-webpack`.
